api/prisma/schema.prisma
api/src/__test__/integration/__snapshots__/activities.spec.ts.snap
api/src/__test__/integration/activities.spec.ts
api/src/controllers/Activities/index.ts
api/src/middleware/errorHandler.ts
api/src/utils/prisma.ts

- Adds integration tests for activities route
- Add unique constraint for activity name and orgId
- Add default error handling for PrismaClient unique constraint errors

Add integration tests for activities

---

api/express.d.ts
api/package.json
api/prisma/schema.prisma
api/src/__test__/helpers/helpers.ts
api/src/__test__/integration/__snapshots__/members.spec.ts.snap
api/src/__test__/integration/activities.spec.ts
api/src/__test__/integration/auth.spec.ts
api/src/__test__/integration/members.spec.ts
api/src/__test__/integration/organizations.spec.ts
api/src/__test__/integration/timelogs.spec.ts
api/src/controllers/Activities/index.ts
api/src/controllers/Auth/index.ts
api/src/controllers/Members/index.ts
api/src/controllers/Organizations/index.ts
api/src/controllers/TimeLogs/index.ts
api/src/middleware/authHandler.ts
api/src/services/activities.ts
api/src/services/auth.ts
api/src/services/members.ts
api/src/services/organizations.ts
api/src/services/timelogs.ts
api/src/services/user.ts
core/constants/package.json
core/constants/roles.ts
core/types/api/activities/index.ts
core/types/api/auth/index.ts
core/types/api/members/index.ts
core/types/api/timelogs/index.ts

- All requests now use req.user to verify agains organization id
- Updated all tests to include auth
- Restrict org/user creation to admins
- Added route protect to remaining routes

Adds remaining route protect, role permission

---

frontend/package.json
frontend/src/main.ts
frontend/src/views/TimeLogging.vue
yarn.lock

Ended up creating a totally new branch for this shait, I've set it up, got it working, and just imported the calendar component into the timesheet page. lmk what u think 'bout it
.

add prime vue

---

frontend/.env.development
frontend/src/App.vue
frontend/src/env.d.ts
frontend/src/router/index.ts
frontend/src/services/auth.ts
frontend/src/utils/api.ts
frontend/src/utils/constants.ts
frontend/src/utils/validate.ts
frontend/src/views/Login.vue

- Sets up env for api calls agains Docker API container
- Adds api module
- Adds Login page and related functionality

38 create login page setup proxy config

---

.github/workflows/tests.yml
frontend/.gitignore
frontend/Dockerfile
frontend/package.json
frontend/src/__test__/mocks/handlers.ts
frontend/src/__test__/mocks/server.ts
frontend/src/__test__/mocks/setup.ts
frontend/src/__test__/utils/api.spec.ts
frontend/src/__test__/utils/validate.spec.ts
frontend/src/__test__/views/Login.spec.ts
frontend/src/main.ts
frontend/src/services/auth.ts
frontend/src/types/ApiError.ts
frontend/src/utils/api.ts
frontend/src/views/Login.vue
frontend/vite.config.ts
package.json
yarn.lock

- sets up vitest for frontend
- integrates tests into github actions
- added tests for login view and auth related functions

Setup vitest, add api and login view tests

---

.github/workflows/docker-image.yml
.github/workflows/tests.yml
README.md
api/.env.dev
api/package.json
api/prisma/seed.ts
api/src/__test__/helpers/globalSetup.ts
api/src/__test__/helpers/setup.ts
package.json

- sets up seed script for local dev
- updates readme, added local dev setup section
- fix migration command in api test setup

Setup seed script, update readme

---

api/package.json
api/src/middleware/errorHandler.ts
frontend/.env.test
frontend/package.json
frontend/src/App.vue
frontend/src/__test__/mocks/handlers.ts
frontend/src/__test__/mocks/helpers.ts
frontend/src/__test__/mocks/setup.ts
frontend/src/__test__/views/Login.spec.ts
frontend/src/main.ts
frontend/src/services/auth.ts
frontend/src/stores/user.ts
frontend/src/views/Login.vue
yarn.lock

- Adds pinia user store and integrate to login view with tests
- Upgrade Prisma to v4

43 setup pinia user store

---

frontend/src/__test__/views/Login.spec.ts
frontend/src/router/index.ts
frontend/src/services/toast.ts
frontend/src/stores/user.ts

Skipping router specific tests due to the verbose nature of integrating vue-router in the tests. Looking for alternatives.

Add route guard and protected routes

---

.github/workflows/docker-image.yml
.github/workflows/tests.yml
docker-compose.dev.yml
e2e/.gitignore
e2e/Dockerfile
e2e/package.json
e2e/playwright.config.ts
e2e/tests/Auth/login.spec.ts
frontend/.env.test
frontend/package.json
frontend/src/__test__/utils/api.spec.ts
frontend/src/components/AppSidebar.vue
frontend/src/views/Dashboard.vue
frontend/src/views/Login.vue
package.json
yarn.lock

sets up playwright integration for headless e2e tests in a docker compose environment

Setup headless playwright CI and inital test

---

CONTRIBUTING.md
README.md
api/README.md
core/README.md
e2e/README.md
frontend/README.md
frontend/vercel.json

58 cleanup readme files

---

e2e/tests/members/members.spec.ts
frontend/package.json
frontend/src/App.vue
frontend/src/__test__/components/AddMember.spec.ts
frontend/src/__test__/mocks/setup.ts
frontend/src/__test__/views/Members.spec.ts
frontend/src/components/AddMember.vue
frontend/src/main.ts
frontend/src/services/members.ts
frontend/src/stores/members.ts
frontend/src/utils/api.ts
frontend/src/views/Members.vue
yarn.lock

Adds ability for user to create new members

66 fe add member functionality

---

.vscode/settings.json
aws_cdk/.gitignore
aws_cdk/app/index.ts
aws_cdk/cdk.json
aws_cdk/jest.config.js
aws_cdk/package.json
aws_cdk/stacks/api_gw-stack.ts
aws_cdk/stacks/auth-stack.ts
aws_cdk/stacks/users-stack.ts
aws_cdk/tsconfig.json
package.json
yarn.lock

Limitations for local setup:
- based on [this issue](https://github.com/aws/aws-sam-cli/issues/3306) aws sam-local does not support running cloudformation templates with nested stacks
- localstack ApiGatewayV2 is not part of the free tier and requires [a paid plan](https://docs.localstack.cloud/references/coverage/coverage_apigatewayv2/) (not viable)
Possible undesired workaround for local setup: locate all CDK stacks in the app

feat(infra): initial cdk app and stack setup

---

.github/workflows/aws_deploy.yml
.github/workflows/release.yml
aws_cdk/configurations/bootstrap/bootstrap.sh
aws_cdk/configurations/bootstrap/cdkCfExecutionPolicy.json
aws_cdk/configurations/oidc_github/iam_policy.json
aws_cdk/configurations/oidc_github/trust_policy_template.json

- Swap workflow_call for correct workflow_dispatch to call action manually
- Add cdk policy and OIDC related policies

feat(infra): add infrastructure policy definitions for dev env

---

.github/workflows/aws_deploy.yml
.github/workflows/aws_ecr_build.yml
.github/workflows/aws_pipeline_api.yml
aws_cdk/lib/api/authorizer.ts
aws_cdk/lib/api/index.ts
aws_cdk/lib/ecr/index.ts
aws_cdk/package.json
yarn.lock

- added ecr lifecycle policies
- image builds and api deployment now use sha instead of latest tag

feat(infra): add ecr repo lifecycle and dynamic image tag values

---

.github/workflows/aws_pipeline_api.yml
.github/workflows/ci.yml

- Rewritten CI workflow to cover migrations and AWS API resource deployments/offboardings

feat(infra): rewrite CI pipeline for new resources

---

.github/workflows/ci.yml
.github/workflows/ci_tests.yml
.github/workflows/db_migrator.yml
aws_cdk/package.json
aws_cdk/test/api/__snapshots__/authorizer.test.ts.snap
aws_cdk/test/api/authorizer.test.ts
aws_cdk/test/ecr/__snapshots__/index.test.ts.snap
aws_cdk/test/ecr/index.test.ts
aws_cdk/test/helpers.ts
compose.ci.yml
core/db/.env.test
core/db/jest.config.js
core/db/package.json
core/db/src/clients/pg.ts
core/db/src/schema/member.ts
core/db/src/schema/time-log.ts
core/db/src/schema/user.ts
core/db/test/__snapshots__/index.test.ts.snap
core/db/test/helpers/globalSetup.ts
core/db/test/helpers/setup.ts
core/db/test/helpers/teardown.ts
core/db/test/index.test.ts
core/db/tsconfig.json
yarn.lock

Sets up workflow for CI tests and adds tests for aws_cdk and core/db

feat(tests): create ci_test workflow and cdk, db tests

---

apps/api/members/test/index.test.ts
packages/db/src/schema/activity-type.ts
packages/db/src/schema/member.ts
packages/db/src/schema/user.ts

fix(db): resolve deprecated index syntax

---

.github/workflows/ci_e2e.yml
apps/e2e/.gitignore
apps/e2e/helpers/apiActions.ts
apps/e2e/helpers/userActions.ts
apps/e2e/helpers/utils.ts
apps/e2e/package.json
apps/e2e/playwright.config.ts
apps/e2e/tests/Auth/login.spec.ts
apps/e2e/tests/members/members.spec.ts
apps/e2e/tests/nav/nav.spec.ts
eslint.config.mjs
infrastructure/lib/api/members.ts
yarn.lock

Closes #123 
- enables the endpoint with E2E testing pipeline

123 create add member api endpoint as previously implemented

---

infrastructure/configurations/bootstrap/bootstrap.sh
infrastructure/configurations/bootstrap/cdkCfExecutionPolicy.json
infrastructure/configurations/oidc_github/trust_policy_template_dev.json
infrastructure/configurations/oidc_github/trust_policy_template_prod.json

closes #129 
- AWS prod account created
- updates/creates relevant trust policies
- fixes a typo for CDK execution policy

chore(infra): update trust policy templates and bootstrap script for dev/prod

---

.github/workflows/release.yml
apps/frontend/vercel.json

closes #131 
- adds production deployment pipeline

feat(infra): create release pipeline
